---
steps:
  - name: Tests
    image: python:3.13-bookworm
    volumes:
      # ci-cache
      - '/volumes/system/ci-cache/behappy:/var/cache/ci-cache'
    environment:
      XDG_CACHE_HOME: /var/cache/ci-cache
    commands:
      - apt-get update -qq && apt-get install -yqq libimage-exiftool-perl
      - pip3 install -r requirements.txt
      - cd src && python -m unittest discover
